import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';
import { ContextProviders } from '@/contexts/providers';
import { cn } from '@/lib/utils';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = 'dark';

  return (
    <html lang="pt">
      <body className={cn('h-svh', 'antialiased', theme, geistSans.variable, geistMono.variable)}>
        <ContextProviders>
          {children}
          <Toaster />
        </ContextProviders>
      </body>
    </html>
  );
}
