import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';
import { ContextProviders } from '@/contexts/providers';
import { cookies, headers } from 'next/headers';
import { cn } from '@/lib/utils';
import { Language } from '@/lib/translations';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesRes = await cookies();
  const initialLang = cookiesRes.get('app_language')?.value;

  return (
    <html lang={initialLang ?? 'pt'}>
      <body className={cn('h-svh', 'antialiased', geistSans.variable, geistMono.variable)}>
        <ContextProviders initialLang={initialLang}>{children}</ContextProviders>
        <Toaster />
      </body>
    </html>
  );
}
